# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindowInterfaz.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 687)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.grammarFrame = QtWidgets.QFrame(self.centralwidget)
        self.grammarFrame.setGeometry(QtCore.QRect(0, 40, 371, 601))
        self.grammarFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.grammarFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.grammarFrame.setObjectName("grammarFrame")
        self.extra1 = QtWidgets.QFrame(self.grammarFrame)
        self.extra1.setGeometry(QtCore.QRect(10, 130, 351, 20))
        self.extra1.setFrameShape(QtWidgets.QFrame.HLine)
        self.extra1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.extra1.setObjectName("extra1")
        self.widget = QtWidgets.QWidget(self.grammarFrame)
        self.widget.setGeometry(QtCore.QRect(10, 10, 351, 111))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.symbolsLabel = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.symbolsLabel.setFont(font)
        self.symbolsLabel.setObjectName("symbolsLabel")
        self.horizontalLayout.addWidget(self.symbolsLabel)
        self.symbolsEdit = QtWidgets.QLineEdit(self.widget)
        self.symbolsEdit.setObjectName("symbolsEdit")
        self.horizontalLayout.addWidget(self.symbolsEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.varsLabel = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.varsLabel.setFont(font)
        self.varsLabel.setObjectName("varsLabel")
        self.horizontalLayout_2.addWidget(self.varsLabel)
        self.varsEdit = QtWidgets.QLineEdit(self.widget)
        self.varsEdit.setObjectName("varsEdit")
        self.horizontalLayout_2.addWidget(self.varsEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.markersLabel = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.markersLabel.setFont(font)
        self.markersLabel.setObjectName("markersLabel")
        self.horizontalLayout_3.addWidget(self.markersLabel)
        self.markersEdit = QtWidgets.QLineEdit(self.widget)
        self.markersEdit.setObjectName("markersEdit")
        self.horizontalLayout_3.addWidget(self.markersEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.widget1 = QtWidgets.QWidget(self.grammarFrame)
        self.widget1.setGeometry(QtCore.QRect(10, 151, 346, 321))
        self.widget1.setObjectName("widget1")
        self.gridLayout = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.rulesLabel = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.rulesLabel.setFont(font)
        self.rulesLabel.setObjectName("rulesLabel")
        self.horizontalLayout_6.addWidget(self.rulesLabel)
        spacerItem = QtWidgets.QSpacerItem(168, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout_6, 0, 0, 1, 2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.putButton = QtWidgets.QPushButton(self.widget1)
        self.putButton.setText("")
        self.putButton.setObjectName("putButton")
        self.verticalLayout_2.addWidget(self.putButton)
        self.removeButton = QtWidgets.QPushButton(self.widget1)
        self.removeButton.setText("")
        self.removeButton.setObjectName("removeButton")
        self.verticalLayout_2.addWidget(self.removeButton)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 128, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.gridLayout.addLayout(self.verticalLayout_3, 1, 0, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.widget1)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidget, 1, 1, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem2 = QtWidgets.QSpacerItem(178, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.splitter = QtWidgets.QSplitter(self.widget1)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.saveButton = QtWidgets.QPushButton(self.splitter)
        self.saveButton.setObjectName("saveButton")
        self.cancelButton = QtWidgets.QPushButton(self.splitter)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout_5.addWidget(self.splitter)
        self.gridLayout.addLayout(self.horizontalLayout_5, 2, 0, 1, 2)
        self.runFrame = QtWidgets.QFrame(self.centralwidget)
        self.runFrame.setGeometry(QtCore.QRect(390, 10, 391, 101))
        self.runFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.runFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.runFrame.setObjectName("runFrame")
        self.lineEdit = QtWidgets.QLineEdit(self.runFrame)
        self.lineEdit.setGeometry(QtCore.QRect(10, 30, 371, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.testLabel = QtWidgets.QLabel(self.runFrame)
        self.testLabel.setGeometry(QtCore.QRect(10, 0, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.testLabel.setFont(font)
        self.testLabel.setObjectName("testLabel")
        self.runButton = QtWidgets.QPushButton(self.runFrame)
        self.runButton.setGeometry(QtCore.QRect(310, 60, 75, 23))
        self.runButton.setObjectName("runButton")
        self.debugButton = QtWidgets.QPushButton(self.runFrame)
        self.debugButton.setGeometry(QtCore.QRect(220, 60, 75, 23))
        self.debugButton.setObjectName("debugButton")
        self.extra2 = QtWidgets.QFrame(self.centralwidget)
        self.extra2.setGeometry(QtCore.QRect(390, 120, 391, 16))
        self.extra2.setFrameShape(QtWidgets.QFrame.HLine)
        self.extra2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.extra2.setObjectName("extra2")
        self.resultFrame = QtWidgets.QFrame(self.centralwidget)
        self.resultFrame.setGeometry(QtCore.QRect(390, 150, 391, 371))
        self.resultFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.resultFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.resultFrame.setObjectName("resultFrame")
        self.resultLabel = QtWidgets.QLabel(self.resultFrame)
        self.resultLabel.setGeometry(QtCore.QRect(10, 10, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.resultLabel.setFont(font)
        self.resultLabel.setObjectName("resultLabel")
        self.printText = QtWidgets.QTextEdit(self.resultFrame)
        self.printText.setGeometry(QtCore.QRect(10, 130, 361, 231))
        self.printText.setObjectName("printText")
        self.ruleLabel = QtWidgets.QLabel(self.resultFrame)
        self.ruleLabel.setGeometry(QtCore.QRect(10, 30, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.ruleLabel.setFont(font)
        self.ruleLabel.setObjectName("ruleLabel")
        self.ruleEdit = QtWidgets.QLineEdit(self.resultFrame)
        self.ruleEdit.setGeometry(QtCore.QRect(110, 30, 161, 20))
        self.ruleEdit.setObjectName("ruleEdit")
        self.afterLabel = QtWidgets.QLabel(self.resultFrame)
        self.afterLabel.setGeometry(QtCore.QRect(10, 50, 41, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.afterLabel.setFont(font)
        self.afterLabel.setObjectName("afterLabel")
        self.afterEdit = QtWidgets.QLineEdit(self.resultFrame)
        self.afterEdit.setGeometry(QtCore.QRect(10, 70, 171, 20))
        self.afterEdit.setObjectName("afterEdit")
        self.beforeEdit = QtWidgets.QLineEdit(self.resultFrame)
        self.beforeEdit.setGeometry(QtCore.QRect(200, 70, 171, 20))
        self.beforeEdit.setObjectName("beforeEdit")
        self.beforeLabel = QtWidgets.QLabel(self.resultFrame)
        self.beforeLabel.setGeometry(QtCore.QRect(210, 50, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.beforeLabel.setFont(font)
        self.beforeLabel.setObjectName("beforeLabel")
        self.nextButton = QtWidgets.QPushButton(self.resultFrame)
        self.nextButton.setGeometry(QtCore.QRect(300, 100, 75, 23))
        self.nextButton.setObjectName("nextButton")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(10, 10, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(12)
        self.title.setFont(font)
        self.title.setObjectName("title")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.symbolsLabel.setText(_translate("MainWindow", "Alfabeto:"))
        self.varsLabel.setText(_translate("MainWindow", "Variables:"))
        self.markersLabel.setText(_translate("MainWindow", "Marcadores:"))
        self.rulesLabel.setText(_translate("MainWindow", "Reglas de producción"))
        self.saveButton.setText(_translate("MainWindow", "Guardar"))
        self.cancelButton.setText(_translate("MainWindow", "Cancelar"))
        self.testLabel.setText(_translate("MainWindow", "Prueba"))
        self.runButton.setText(_translate("MainWindow", "Run"))
        self.debugButton.setText(_translate("MainWindow", "Debug"))
        self.resultLabel.setText(_translate("MainWindow", "Resultado"))
        self.printText.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.ruleLabel.setText(_translate("MainWindow", "Regla por aplicar:"))
        self.afterLabel.setText(_translate("MainWindow", "Antes:"))
        self.beforeLabel.setText(_translate("MainWindow", "Despues:"))
        self.nextButton.setText(_translate("MainWindow", "Siguiente"))
        self.title.setText(_translate("MainWindow", "Traducción"))

