# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindowInterfaz.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(730, 704)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.grammarFrame = QtWidgets.QFrame(self.centralwidget)
        self.grammarFrame.setGeometry(QtCore.QRect(0, 40, 351, 481))
        self.grammarFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.grammarFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.grammarFrame.setObjectName("grammarFrame")
        self.extra1 = QtWidgets.QFrame(self.grammarFrame)
        self.extra1.setGeometry(QtCore.QRect(10, 130, 351, 20))
        self.extra1.setFrameShape(QtWidgets.QFrame.HLine)
        self.extra1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.extra1.setObjectName("extra1")
        self.layoutWidget = QtWidgets.QWidget(self.grammarFrame)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 331, 111))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.symbolsLabel = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.symbolsLabel.setFont(font)
        self.symbolsLabel.setObjectName("symbolsLabel")
        self.horizontalLayout.addWidget(self.symbolsLabel)
        self.symbolsEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.symbolsEdit.setEnabled(True)
        self.symbolsEdit.setText("")
        self.symbolsEdit.setObjectName("symbolsEdit")
        self.horizontalLayout.addWidget(self.symbolsEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.varsLabel = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.varsLabel.setFont(font)
        self.varsLabel.setObjectName("varsLabel")
        self.horizontalLayout_2.addWidget(self.varsLabel)
        self.varsEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.varsEdit.setEnabled(True)
        self.varsEdit.setText("")
        self.varsEdit.setObjectName("varsEdit")
        self.horizontalLayout_2.addWidget(self.varsEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.markersLabel = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.markersLabel.setFont(font)
        self.markersLabel.setObjectName("markersLabel")
        self.horizontalLayout_3.addWidget(self.markersLabel)
        self.markersEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.markersEdit.setEnabled(True)
        self.markersEdit.setText("")
        self.markersEdit.setObjectName("markersEdit")
        self.horizontalLayout_3.addWidget(self.markersEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.layoutWidget1 = QtWidgets.QWidget(self.grammarFrame)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 151, 331, 321))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.rulesLabel = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.rulesLabel.setFont(font)
        self.rulesLabel.setObjectName("rulesLabel")
        self.horizontalLayout_6.addWidget(self.rulesLabel)
        spacerItem = QtWidgets.QSpacerItem(168, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout_6, 0, 0, 1, 2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.grammarEdit = QtWidgets.QTextEdit(self.layoutWidget1)
        self.grammarEdit.setObjectName("grammarEdit")
        self.verticalLayout_2.addWidget(self.grammarEdit)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout_3, 1, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem1 = QtWidgets.QSpacerItem(178, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.clearButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.clearButton.setEnabled(True)
        self.clearButton.setObjectName("clearButton")
        self.horizontalLayout_5.addWidget(self.clearButton)
        self.saveButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.saveButton.setEnabled(True)
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout_5.addWidget(self.saveButton)
        self.gridLayout.addLayout(self.horizontalLayout_5, 2, 0, 1, 2)
        self.runFrame = QtWidgets.QFrame(self.centralwidget)
        self.runFrame.setGeometry(QtCore.QRect(360, 10, 361, 101))
        self.runFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.runFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.runFrame.setObjectName("runFrame")
        self.lineEdit = QtWidgets.QLineEdit(self.runFrame)
        self.lineEdit.setGeometry(QtCore.QRect(10, 30, 341, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.testLabel = QtWidgets.QLabel(self.runFrame)
        self.testLabel.setGeometry(QtCore.QRect(10, 0, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.testLabel.setFont(font)
        self.testLabel.setObjectName("testLabel")
        self.runButton = QtWidgets.QPushButton(self.runFrame)
        self.runButton.setGeometry(QtCore.QRect(280, 60, 75, 23))
        self.runButton.setObjectName("runButton")
        self.debugButton = QtWidgets.QPushButton(self.runFrame)
        self.debugButton.setGeometry(QtCore.QRect(200, 60, 75, 23))
        self.debugButton.setObjectName("debugButton")
        self.extra2 = QtWidgets.QFrame(self.centralwidget)
        self.extra2.setGeometry(QtCore.QRect(360, 120, 361, 16))
        self.extra2.setFrameShape(QtWidgets.QFrame.HLine)
        self.extra2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.extra2.setObjectName("extra2")
        self.resultFrame = QtWidgets.QFrame(self.centralwidget)
        self.resultFrame.setGeometry(QtCore.QRect(360, 140, 361, 381))
        self.resultFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.resultFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.resultFrame.setObjectName("resultFrame")
        self.resultLabel = QtWidgets.QLabel(self.resultFrame)
        self.resultLabel.setGeometry(QtCore.QRect(10, 10, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.resultLabel.setFont(font)
        self.resultLabel.setObjectName("resultLabel")
        self.printText = QtWidgets.QTextEdit(self.resultFrame)
        self.printText.setGeometry(QtCore.QRect(10, 130, 341, 241))
        self.printText.setObjectName("printText")
        self.ruleLabel = QtWidgets.QLabel(self.resultFrame)
        self.ruleLabel.setGeometry(QtCore.QRect(10, 30, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.ruleLabel.setFont(font)
        self.ruleLabel.setObjectName("ruleLabel")
        self.ruleEdit = QtWidgets.QLineEdit(self.resultFrame)
        self.ruleEdit.setGeometry(QtCore.QRect(110, 30, 161, 20))
        self.ruleEdit.setObjectName("ruleEdit")
        self.afterLabel = QtWidgets.QLabel(self.resultFrame)
        self.afterLabel.setGeometry(QtCore.QRect(10, 50, 41, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.afterLabel.setFont(font)
        self.afterLabel.setObjectName("afterLabel")
        self.afterEdit = QtWidgets.QLineEdit(self.resultFrame)
        self.afterEdit.setGeometry(QtCore.QRect(10, 70, 141, 20))
        self.afterEdit.setObjectName("afterEdit")
        self.beforeEdit = QtWidgets.QLineEdit(self.resultFrame)
        self.beforeEdit.setGeometry(QtCore.QRect(190, 70, 161, 20))
        self.beforeEdit.setObjectName("beforeEdit")
        self.beforeLabel = QtWidgets.QLabel(self.resultFrame)
        self.beforeLabel.setGeometry(QtCore.QRect(190, 50, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.beforeLabel.setFont(font)
        self.beforeLabel.setObjectName("beforeLabel")
        self.nextButton = QtWidgets.QPushButton(self.resultFrame)
        self.nextButton.setGeometry(QtCore.QRect(280, 100, 75, 23))
        self.nextButton.setObjectName("nextButton")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(10, 10, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(12)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 520, 331, 131))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridButton = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridButton.setContentsMargins(0, 0, 0, 0)
        self.gridButton.setObjectName("gridButton")
        self.b7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.b7.setObjectName("b7")
        self.gridButton.addWidget(self.b7, 1, 6, 1, 1)
        self.b5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.b5.setObjectName("b5")
        self.gridButton.addWidget(self.b5, 1, 4, 1, 1)
        self.b6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.b6.setObjectName("b6")
        self.gridButton.addWidget(self.b6, 1, 5, 1, 1)
        self.b11 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.b11.setObjectName("b11")
        self.gridButton.addWidget(self.b11, 1, 10, 1, 1)
        self.b9 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.b9.setObjectName("b9")
        self.gridButton.addWidget(self.b9, 1, 8, 1, 1)
        self.b10 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.b10.setObjectName("b10")
        self.gridButton.addWidget(self.b10, 1, 9, 1, 1)
        self.b8 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.b8.setObjectName("b8")
        self.gridButton.addWidget(self.b8, 1, 7, 1, 1)
        self.b39 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.b39.setObjectName("b39")
        self.gridButton.addWidget(self.b39, 4, 12, 1, 1)
        self.b13 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.b13.setObjectName("b13")
        self.gridButton.addWidget(self.b13, 1, 12, 1, 1)
        self.b12 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.b12.setObjectName("b12")
        self.gridButton.addWidget(self.b12, 1, 11, 1, 1)
        self.b15 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.b15.setObjectName("b15")
        self.gridButton.addWidget(self.b15, 2, 1, 1, 1)
        self.b18 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.b18.setObjectName("b18")
        self.gridButton.addWidget(self.b18, 2, 4, 1, 1)
        self.b17 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.b17.setObjectName("b17")
        self.gridButton.addWidget(self.b17, 2, 3, 1, 1)
        self.b16 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.b16.setObjectName("b16")
        self.gridButton.addWidget(self.b16, 2, 2, 1, 1)
        self.b19 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.b19.setObjectName("b19")
        self.gridButton.addWidget(self.b19, 2, 5, 1, 1)
        self.b21 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.b21.setObjectName("b21")
        self.gridButton.addWidget(self.b21, 2, 7, 1, 1)
        self.b23 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.b23.setObjectName("b23")
        self.gridButton.addWidget(self.b23, 2, 9, 1, 1)
        self.b22 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.b22.setObjectName("b22")
        self.gridButton.addWidget(self.b22, 2, 8, 1, 1)
        self.b20 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.b20.setObjectName("b20")
        self.gridButton.addWidget(self.b20, 2, 6, 1, 1)
        self.b24 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.b24.setObjectName("b24")
        self.gridButton.addWidget(self.b24, 2, 10, 1, 1)
        self.b26 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.b26.setObjectName("b26")
        self.gridButton.addWidget(self.b26, 2, 12, 1, 1)
        self.b25 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.b25.setObjectName("b25")
        self.gridButton.addWidget(self.b25, 2, 11, 1, 1)
        self.b29 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.b29.setObjectName("b29")
        self.gridButton.addWidget(self.b29, 4, 2, 1, 1)
        self.b30 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.b30.setObjectName("b30")
        self.gridButton.addWidget(self.b30, 4, 3, 1, 1)
        self.b33 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.b33.setObjectName("b33")
        self.gridButton.addWidget(self.b33, 4, 6, 1, 1)
        self.b34 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.b34.setObjectName("b34")
        self.gridButton.addWidget(self.b34, 4, 7, 1, 1)
        self.b31 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.b31.setObjectName("b31")
        self.gridButton.addWidget(self.b31, 4, 4, 1, 1)
        self.b32 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.b32.setObjectName("b32")
        self.gridButton.addWidget(self.b32, 4, 5, 1, 1)
        self.b35 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.b35.setObjectName("b35")
        self.gridButton.addWidget(self.b35, 4, 8, 1, 1)
        self.b36 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.b36.setObjectName("b36")
        self.gridButton.addWidget(self.b36, 4, 9, 1, 1)
        self.b37 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.b37.setObjectName("b37")
        self.gridButton.addWidget(self.b37, 4, 10, 1, 1)
        self.b28 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.b28.setObjectName("b28")
        self.gridButton.addWidget(self.b28, 4, 1, 1, 1)
        self.b1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.b1.setObjectName("b1")
        self.gridButton.addWidget(self.b1, 1, 0, 1, 1)
        self.b14 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.b14.setObjectName("b14")
        self.gridButton.addWidget(self.b14, 2, 0, 1, 1)
        self.b27 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.b27.setObjectName("b27")
        self.gridButton.addWidget(self.b27, 4, 0, 1, 1)
        self.b38 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.b38.setObjectName("b38")
        self.gridButton.addWidget(self.b38, 4, 11, 1, 1)
        self.b3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.b3.setObjectName("b3")
        self.gridButton.addWidget(self.b3, 1, 2, 1, 1)
        self.b4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.b4.setObjectName("b4")
        self.gridButton.addWidget(self.b4, 1, 3, 1, 1)
        self.b2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.b2.setObjectName("b2")
        self.gridButton.addWidget(self.b2, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridButton.addWidget(self.label, 0, 0, 1, 5)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridButton.addWidget(self.label_2, 3, 0, 1, 5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 730, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.symbolsLabel.setText(_translate("MainWindow", "Alfabeto:"))
        self.varsLabel.setText(_translate("MainWindow", "Variables:"))
        self.markersLabel.setText(_translate("MainWindow", "Marcadores:"))
        self.rulesLabel.setText(_translate("MainWindow", "Reglas de producción"))
        self.clearButton.setText(_translate("MainWindow", "Limpiar"))
        self.saveButton.setText(_translate("MainWindow", "Guardar"))
        self.testLabel.setText(_translate("MainWindow", "Prueba"))
        self.runButton.setText(_translate("MainWindow", "Run"))
        self.debugButton.setText(_translate("MainWindow", "Debug"))
        self.resultLabel.setText(_translate("MainWindow", "Resultado"))
        self.printText.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.ruleLabel.setText(_translate("MainWindow", "Regla por aplicar:"))
        self.afterLabel.setText(_translate("MainWindow", "Antes:"))
        self.beforeLabel.setText(_translate("MainWindow", "Despues:"))
        self.nextButton.setText(_translate("MainWindow", "Siguiente"))
        self.title.setText(_translate("MainWindow", "Traducción"))
        self.b7.setText(_translate("MainWindow", "η"))
        self.b5.setText(_translate("MainWindow", "ε"))
        self.b6.setText(_translate("MainWindow", "ζ"))
        self.b11.setText(_translate("MainWindow", "λ"))
        self.b9.setText(_translate("MainWindow", "ι"))
        self.b10.setText(_translate("MainWindow", "κ"))
        self.b8.setText(_translate("MainWindow", "θ"))
        self.b39.setText(_translate("MainWindow", ">"))
        self.b13.setText(_translate("MainWindow", "ν"))
        self.b12.setText(_translate("MainWindow", "μ"))
        self.b15.setText(_translate("MainWindow", "ο"))
        self.b18.setText(_translate("MainWindow", "σ"))
        self.b17.setText(_translate("MainWindow", "ρ"))
        self.b16.setText(_translate("MainWindow", "π"))
        self.b19.setText(_translate("MainWindow", "ς"))
        self.b21.setText(_translate("MainWindow", "υ"))
        self.b23.setText(_translate("MainWindow", "χ"))
        self.b22.setText(_translate("MainWindow", "φ"))
        self.b20.setText(_translate("MainWindow", "τ"))
        self.b24.setText(_translate("MainWindow", "ψ"))
        self.b26.setText(_translate("MainWindow", "Λ"))
        self.b25.setText(_translate("MainWindow", "ω"))
        self.b29.setText(_translate("MainWindow", "_"))
        self.b30.setText(_translate("MainWindow", "-"))
        self.b33.setText(_translate("MainWindow", "/"))
        self.b34.setText(_translate("MainWindow", "."))
        self.b31.setText(_translate("MainWindow", "*"))
        self.b32.setText(_translate("MainWindow", "\""))
        self.b35.setText(_translate("MainWindow", ","))
        self.b36.setText(_translate("MainWindow", "("))
        self.b37.setText(_translate("MainWindow", ")"))
        self.b28.setText(_translate("MainWindow", "%"))
        self.b1.setText(_translate("MainWindow", "α"))
        self.b14.setText(_translate("MainWindow", "ξ"))
        self.b27.setText(_translate("MainWindow", "->"))
        self.b38.setText(_translate("MainWindow", ":"))
        self.b3.setText(_translate("MainWindow", "γ"))
        self.b4.setText(_translate("MainWindow", "δ"))
        self.b2.setText(_translate("MainWindow", "β"))
        self.label.setText(_translate("MainWindow", " Alfabeto Griego"))
        self.label_2.setText(_translate("MainWindow", "Simbolos especiales"))

